// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

/// <summary>
/// Entitet koji predstavlja posao.
/// </summary>
[Table("posao")]
public partial class Posao
{
    /// <summary>
    ///  Jedinstveni identifikator posla
    /// </summary>
    [Key]
    [Column("idPosla")]
    public int IdPosla { get; set; }

    /// <summary>
    /// Opis posla
    /// </summary>

    [Column("opis", TypeName = "text")]
    public string Opis { get; set; }

    /// <summary>
    /// Ime posla
    /// </summary>

    [Required]
    [Column("imePosla", TypeName = "text")]
    public string ImePosla { get; set; }

    /// <summary>
    /// Jedinstveni identifikator vrste posla
    /// </summary>

    [Column("idVrste")]
    public int IdVrste { get; set; }

    /// <summary>
    /// Navigacijski svojstvo koje predstavlja vrstu posla povezanog s ovim poslom
    /// </summary>

    [ForeignKey("IdVrste")]
    [InverseProperty("Posao")]
    public virtual VrstaPosla IdVrsteNavigation { get; set; }
    /// <summary>
    /// Kolekcija osoba povezanih s ovim poslom.
    /// </summary>

    [ForeignKey("IdPosla")]
    [InverseProperty("IdPosla")]
    public virtual ICollection<Osoba> IdOsoba { get; set; } = new List<Osoba>();
}