// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

[Table("status")]
public partial class Status
{
    [Key]
    [Column("idStatusa")]
    public int IdStatusa { get; set; }

    [Required]
    [Column("imeStatusa", TypeName = "text")]
    public string ImeStatusa { get; set; }

    [InverseProperty("IdStatusaNavigation")]
    public virtual ICollection<Zadatak> Zadatak { get; set; } = new List<Zadatak>();
}