// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

/// <summary>
/// Tablica "transakcija" iz baze podataka.
/// </summary>
[Table("transakcija")]
public partial class Transakcija
{
    /// <summary>
    /// Model transakcije.
    /// </summary>
    [Column("model", TypeName = "varchar(50)")]
    public string Model { get; set; }

    /// <summary>
    /// ID transakcije.
    /// </summary>
    [Key]
    [Column("idTrans")]
    public int IdTrans { get; set; }

    /// <summary>
    /// Opis transakcije.
    /// </summary>
    [Column("opis", TypeName = "varchar(MAX)")]
    public string Opis { get; set; }

    /// <summary>
    /// Iznos transakcije.
    /// </summary>
    [Column("iznos", TypeName = "decimal(18, 0)")]
    public decimal Iznos { get; set; }

    /// <summary>
    /// Vrijeme transakcije.
    /// </summary>
    [Column("datum", TypeName = "datetime")]
    public DateTime? Datum { get; set; }

    /// <summary>
    /// Poziv na broj transakcije
    /// </summary>
    [Column("pozivNaBr")]
    public int? PozivNaBr { get; set; }

    /// <summary>
    /// Broj kartice
    /// </summary>
    [Column("brKartice")]
    public int BrKartice { get; set; }

    /// <summary>
    /// ID vrste transakcije
    /// </summary>
    [Column("idVrste")]
    public int IdVrste { get; set; }

    /// <summary>
    /// Objekt kartice uz koju je vezana transakcija
    /// </summary>
    [ForeignKey("BrKartice")]
    [InverseProperty("Transakcija")]
    public virtual Kartica BrKarticeNavigation { get; set; }

    /// <summary>
    /// Objekt vrste transakcije uz koji je vezana transackija
    /// </summary>
    [ForeignKey("IdVrste")]
    [InverseProperty("Transakcija")]
    public virtual VrstaTransakcije IdVrsteNavigation { get; set; }
}