// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

[Table("zadatak")]
public partial class Zadatak
{
    [Required]
    [Column("naslov", TypeName = "text")]
    public string Naslov { get; set; }

    [Column("planKraj", TypeName = "date")]
    public DateTime PlanKraj { get; set; }

    [Column("stvKraj", TypeName = "date")]
    public DateTime? StvKraj { get; set; }

    [Column("planPocetak", TypeName = "date")]
    public DateTime PlanPocetak { get; set; }

    [Required]
    [Column("opis", TypeName = "text")]
    public string Opis { get; set; }

    [Column("stvPoc", TypeName = "date")]
    public DateTime? StvPoc { get; set; }

    [Key]
    [Column("idZadatka")]
    public int IdZadatka { get; set; }

    [Required]
    [Column("prioritet", TypeName = "text")]
    public string Prioritet { get; set; }

    [Column("idZahtjeva")]
    public int IdZahtjeva { get; set; }

    [Column("idStatusa")]
    public int IdStatusa { get; set; }

    [Column("idOsoba")]
    public int? IdOsoba { get; set; }

    [ForeignKey("IdOsoba")]
    [InverseProperty("Zadatak")]
    public virtual Osoba IdOsobaNavigation { get; set; }

    [ForeignKey("IdStatusa")]
    [InverseProperty("Zadatak")]
    public virtual Status IdStatusaNavigation { get; set; }

    [ForeignKey("IdZahtjeva")]
    [InverseProperty("Zadatak")]
    public virtual Zahtjev IdZahtjevaNavigation { get; set; }
}